# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Docker compose set of services to locally run the tests sequentially using
# Node 20, 22, 24 LTS versions.
#
# Usage:
# UIDGID="$(id -u):$(id -g)" docker compose  --file=./docker-compose.test.yaml up

services:
  node_20_tests:
    container_name: node_20_tests
    image: node:20.20.0-slim
    working_dir: /app
    entrypoint: ["/bin/bash", "-e", "-x", "-c"]
    command:
      - "npm ci --engine-strict=true && npm test && npm audit"
    volumes:
      - .:/app

  node_22_tests:
    container_name: node_22_tests
    image: node:22.22-slim
    working_dir: /app
    entrypoint: ["/bin/bash", "-e", "-x", "-c"]
    command:
      - "npm ci --engine-strict=true && npm test && npm audit "
    volumes:
      - .:/app
    depends_on:
      node_20_tests:
        condition: service_completed_successfully

  node_24_tests:
    container_name: node_24_tests
    image: node:24.13-slim
    working_dir: /app
    entrypoint: ["/bin/bash", "-e", "-x", "-c"]
    command:
      - "npm ci --engine-strict=true && npm test && npm audit"
    volumes:
      - .:/app
    depends_on:
      node_22_tests:
        condition: service_completed_successfully

  cleanup:
    container_name: cleanup
    image: node:24.13-slim
    working_dir: /app
    entrypoint: ["/bin/bash", "-e", "-x", "-c"]
    command:
      # Node modules will be owned by root, so delete
      - "rm -fr ./node_modules ./coverage"
    volumes:
      - .:/app
    depends_on:
      node_24_tests:
        condition: service_completed_successfully
